parameters:

services:
    jtc_default.jtc_twig_extension:
        class: Jtc\DefaultBundle\TwigExtension\JtcTwigExtension
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension}
