<?php

namespace Jtc\DefaultBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Jtc\DefaultBundle\Entity\FirstUser;

/**
 * FirstUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FirstUserRepository extends EntityRepository {

    /**
     * Reccupère les dernières annonces
     * @return array
     */
    public function getLastAvis($type = null, $limit = null) {
        $qb = $this->createQueryBuilder('a');
        if ($type !== null) {
            $qb->where('a.livredor = :type')->setParameter('type', $type);
        }
        
        if ($limit !== null) {
            $qb->setMaxResults($limit);
        }

        $qb->add('orderBy', 'a.dateMaj DESC');
        return $qb->getQuery()->getResult();
    }

}
