parameters:
#    jtc_user.example.class: Jtc\UserBundle\Example
    my_user.facebook_provider : Jtc\UserBundle\Security\User\Provider\FacebookProvider

services:
    jtc_user.registration.form.type:
        class: Jtc\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: jtc_registration }
            
    jtc_user.profile.form.type:
        class: Jtc\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: jtc_profile }

    my_user.facebook_provider:
        class : "%my_user.facebook_provider%"
        arguments:
            facebook: "@fos_facebook.api"
            userManager: "@fos_user.user_manager"
            validator: "@validator"
            container: "@service_container"
