parameters:
#    jtc_user.example.class: Jtc\UserBundle\Example

services:
    jtc_user.registration.form.type:
        class: Jtc\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: jtc_registration }
            
    jtc_user.profile.form.type:
        class: Jtc\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: jtc_profile }
            
    my.facebook.user:
        class: Jtc\UserBundle\Security\User\Provider\FacebookProvider
        arguments:
            userManager: "@fos_user.user_manager"
            validator: "@validator"