jtc_annonce_homepage:
    pattern:  /
    defaults: { _controller: JtcAnnonceBundle:Default:index }
    
jtc_annonce_create:
    pattern:  /ajouter
    defaults: { _controller: JtcAnnonceBundle:Default:create }
    
jtc_annonce_complete:
    pattern:  /complete/{id}
    defaults: { _controller: JtcAnnonceBundle:Default:complete }

jtc_annonce_show:
    pattern:  /annonce/{id}
    defaults: { _controller: JtcAnnonceBundle:Default:show }
    
jtc_annonce_edit:
    pattern:  /annonce/{id}/edit
    defaults: { _controller: JtcAnnonceBundle:Default:edit }
    
jtc_annonce_delete:
    pattern:  /annonce/{id}/delete
    defaults: { _controller: JtcAnnonceBundle:Default:delete }

jtc_annonce_mes_annonces:
    pattern:  /mesannonces
    defaults: { _controller: JtcAnnonceBundle:Default:mesAnnonces }

jtc_annonce_voyageurs:
    pattern:  /voyageurs
    defaults: { _controller: JtcAnnonceBundle:Default:voyageurs }
    
jtc_annonce_expediteurs:
    pattern:  /expediteurs
    defaults: { _controller: JtcAnnonceBundle:Default:expediteurs }

jtc_annonce_documents:
    pattern:  /documents
    defaults: { _controller: JtcAnnonceBundle:Default:documents }
    
jtc_annonce_search:
    pattern:  /recherche/{type}/
    defaults: { _controller: JtcAnnonceBundle:Default:search }
    
jtc_annonce_contact:
    pattern:  /contact/{id}
    defaults: { _controller: JtcAnnonceBundle:Default:contact }