jtc_annonce_homepage:
    pattern:  /
    defaults: { _controller: JtcAnnonceBundle:Default:index }
    
jtc_annonce_create:
    pattern:  /ajouter
    defaults: { _controller: JtcAnnonceBundle:Default:create }
    
jtc_annonce_complete:
    pattern:  /complete/{id}
    defaults: { _controller: JtcAnnonceBundle:Default:complete }

jtc_annonce_show:
    pattern:  /annonce/{id}
    defaults: { _controller: JtcAnnonceBundle:Default:show }

jtc_annonce_mes_annonces:
    pattern:  /mesannonces
    defaults: { _controller: JtcAnnonceBundle:Default:mesAnnonces }

jtc_annonce_voyageurs:
    pattern:  /voyageurs
    defaults: { _controller: JtcAnnonceBundle:Default:voyageurs }
    
jtc_annonce_expediteurs:
    pattern:  /expediteurs
    defaults: { _controller: JtcAnnonceBundle:Default:expediteurs }