<?php

namespace Jtc\AnnonceBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Jtc\UserBundle\Entity\User;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends EntityRepository
{

    /**
     * Reccupère les dernières annonces
     * @return array
     */
    public function getLastAnnonce($type = null, $limit = null)
    {
        $qb = $this->createQueryBuilder('a');
        if ($type != null) {
            $qb->where('a.type = :type')->setParameter('type', $type);
        }
        if ($limit != null) {
            $qb->setMaxResults($limit);
        }

        $qb->add('orderBy', 'a.dateMaj DESC');
        return $qb->getQuery()->getResult();
    }

    /**
     * Reccupère les annonce qui partent dans la journée
     * @return array
     */
    public function getLeavingToday()
    {
        $today = date("Y-m-d");
        $qb = $this->createQueryBuilder('a');
        $qb->where('a.dateDepart = :today')
                ->setParameter('today', $today);
        $qb->setMaxResults('10');
        $qb->add('orderBy', 'a.dateDepart DESC');
        
        return $qb->getQuery()->getResult();
    }
    
    /**
     * 
     * @param type $user
     * @return type
     */
    public function getAnnoncesFromUser($user)
    {
        $qb = $this->createQueryBuilder('a');
        $qb
                ->where('a.utilisateur = :user')
                ->setParameter(':user', $user)
                ->orderBy('a.dateMaj', 'DESC');
        
        return $qb->getQuery()->getResult();
    }
    
    public function doSearch($data) 
    {
        $ville_depart = $data['ville_depart'];
        $ville_arrive = $data['ville_arrive'];
        $poids = $data['poids'];
        $prix = $data['prix'];
        $type = $data['type'];

        $qb = $this->createQueryBuilder('a');
        if ($data['date_depart'] != '') {
            $date = date('Y-m-d H:i:s', strtotime($data['date_depart']));
            $qb->where('a.dateDepart = :date_depart')
                    ->setParameter('date_depart', $date);
        }

        if ($ville_depart != "") {
            $qb->andWhere('a.villeDepart = :ville_depart')
                    ->setParameter('ville_depart', $ville_depart);
        }


        if ($ville_arrive != "") {
            $qb->andWhere('a.villeArrive = :ville_arrive')
                    ->setParameter('ville_arrive', $ville_arrive);
        }

        if ($poids != "") {
            $qb->andWhere('a.poids = :poids')
                    ->setParameter('poids', $poids);
        }

        if ($prix != "") {
            $qb->andWhere('a.prix = :prix')
                    ->setParameter('prix', $prix);
        }
        
        if ($type != "") {
            $qb->andWhere('a.type = :type')
                    ->setParameter('type', $type);
        }

        $qb->add('orderBy', 'a.dateDepart ASC');
        return $qb;
    }
}
