<?php

namespace Jtc\AnnonceBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Jtc\UserBundle\Entity\User;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends EntityRepository
{

    /**
     * Reccupère les dernières annonces
     * @return array
     */
    public function getLastAnnonce()
    {
        $qb = $this->createQueryBuilder('a');
        $qb->setMaxResults('10');
        $qb->add('orderBy', 'a.dateMaj DESC');
        
        return $qb->getQuery()->getResult();
    }

    /**
     * Reccupère les annonce qui partent dans la journée
     * @return array
     */
    public function getLeavingToday()
    {
        $today = date("Y-m-d");
        $qb = $this->createQueryBuilder('a');
        $qb->where('a.dateDepart = :today')
                ->setParameter('today', $today);
        $qb->setMaxResults('10');
        $qb->add('orderBy', 'a.dateDepart DESC');
        
        return $qb->getQuery()->getResult();
    }
    
    /**
     * 
     * @param type $user
     * @return type
     */
    public function getAnnoncesFromUser($user)
    {
        $qb = $this->createQueryBuilder('a');
        $qb
                ->where('a.utilisateur = :user')
                ->setParameter(':user', $user)
                ->orderBy('a.dateMaj', 'DESC');
        
        return $qb->getQuery()->getResult();
    }
}
